default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

default_stages:
  - pre-commit
  - commit-msg
  - pre-push

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

# -   repo: https://github.com/enabletechnologies/pre-commit-hooks
#     rev: v0.1.1
#     hooks:
#     -   id: commitizen
#     -   id: ruff
#         args: [--fix, --exit-non-zero-on-fix]
#     -   id: pyupgrade
#         args:
#         - --py3-plus
#         - --keep-runtime-typing
#     -   id: codespell
#     -   id: black
