default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

default_stages:
  - pre-commit
  - commit-msg
  - pre-push

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    - id: check-json

# -   repo: https://github.com/enabletechnologies/pre-commit-hooks
#     rev: v0.1.2
#     hooks:
#     -   id: commitizen
#     -   id: ruff
#         args: [--fix, --exit-non-zero-on-fix]
#     -   id: black
    # -   id: typos
