default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/enabletechnologies/pre-commit-hooks
    rev: v0.1.11
    hooks:
      - id: commitizen
      - id: lint
      - id: check_poetry_toml
