default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    - id: check-json

-   repo: https://github.com/enabletechnologies/pre-commit-hooks
    rev: v0.1.6
    hooks:
    -   id: commitizen
    -   id: lint

