- id: commitizen
  name: commitizen check
  description: >
    Check whether the current commit message follows commiting rules. Allow
    empty commit messages by default, because they typically indicate to Git
    that the commit should be aborted.
  entry: cz check
  args: [--allow-abort, --commit-msg-file]
  stages: [commit-msg]
  language: python
  language_version: python3
  minimum_pre_commit_version: "3.3.3"
- id: lint
  name: lint
  entry: make
  args: ["lint"]
  pass_filenames: false
  language: python
  stages: [pre-commit]
  minimum_pre_commit_version: "3.3.3"
- id: check_poetry_toml
  name: lint pyproject.toml
  description: checks pyproject.toml files for parseable syntax path dependency.
  entry: check_poetry_toml
  language: python
  types: [toml]
  files: pyproject.toml
  stages: [pre-commit]
  minimum_pre_commit_version: "3.3.3"
- id: format_mdj
  name: format_mdj
  entry: make
  args: ["format_mdj"]
  pass_filenames: false
  language: python
  stages: [pre-commit]
  minimum_pre_commit_version: "3.3.3"
