[tool.commitizen]
version = "0.0.3"
tag_format = "v$version"
update_changelog_on_bump = true
version_files = [
  "pyproject.toml:version",
  "src/pre-commit-hooks/__init__.py",
  ".pre-commit-config.yaml:rev:.+Commitizen",
  "VERSION"
]
[tool.poetry]
name = "pre-commit-hooks"
version = "0.0.3"
description = "A project to contain all pre-commit hooks for enable technologies"
authors = ["Cloudops <cloudops@enabletechnologies.com>"]
keywords = ["precommit", "conventional", "commits", "git"]
license = "Proprietary"
readme = "README.md"
packages = [{include = "enabletechnologies", from = "src"}]


[tool.poetry.dependencies]
python = "^3.11"
black = "^23.3.0"
isort = "^5.12.0"
pytest = "^7.4.0"
flake8 = "^6.0.0"


[tool.poetry.group.dev.dependencies]

mypy = "^1.4.1"
coverage = "^7.2.7"
#pre-commit = "^3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
