[tool.commitizen]
version = "0.1.15"
tag_format = "v$version"
update_changelog_on_bump = true
version_files = [
  "pyproject.toml:version",
  "src/enable/pre_commit_hooks/__init__.py",
  "VERSION"
]
[tool.poetry]
name = "enable_pre_commit_hooks"
version = "0.1.15"
description = "A project to contain all pre-commit hooks for enable technologies"
authors = ["Cloudops <cloudops@enabletechnologies.com>"]
keywords = ["precommit", "conventional", "commits", "git"]
license = "Proprietary"
readme = "README.md"
packages = [{include = "enable", from = "src"}]


[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pytest = "^7.4.0"
coverage = "^7.2.7"
ruff = "^0.0.277"
mypy = "^1.4.1"
typos = "^1.15.10"

[tool.poetry.scripts]
check_poetry_toml = "enable.pre_commit_hooks.check_poetry_toml:main"

[tool.black]
line-length = 120

[tool.ruff]
# https://beta.ruff.rs/docs/rules/
# pycodestyle (E) pycodestyle warnings (W) pyflakes (F) flake8-bugbear (B) isort (I) pep8-naming (N) 
# flake8-quotes (Q) pydocstyle (D) Copyright-related rules (CPY) pyupgrade (UP) flake8-comprehensions (C4)
select = ["E", "W", "F", "B", "Q", "I", "N", "Q", "D", "C4", "CPY001"]
line-length = 120

[tool.ruff.pydocstyle]
# Use Google-style docstrings.
convention = "google"

[tool.ruff.flake8-copyright]
author = "Enable Technologies Inc"
notice-rgx = "(?i)Copyright © \\d{4}"

[tool.mypy]
strict = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
